/*******************************************************************************
 * Copyright (C) 2020, Yasir Khan <yasir_electronics@yahoo.com>
 * All rights reserved.
 * 
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 * 
 * 1. Redistributions of source code must retain the above copyright notice,
 *    this list of conditions and the following disclaimer.
 * 
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 * 
 * 3. Neither the name of the copyright holder nor the names of its contributors
 *    may be used to endorse or promote products derived from this software
 *    without specific prior written permission.
 * 
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
 * ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE
 * LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
 * CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
 * SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
 * INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
 * CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
 * ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 ******************************************************************************/
/**
  ******************************************************************************
  * @file    main.c
  * @author  Auto-generated by STM32CubeIDE
  * @version V1.0
  * @brief   Default main function.
  ******************************************************************************
*/

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdio.h>

#include <os.h>

void task1(void *data);	// task1
void task2(void *data);	// task2
void task3(void *data);	// task3
void task4(void *data);	// task4

int main(void)
{
	os_init();	// initialize RTOS

	// if SP is MSP, it means the  interrupted context was exception handler.
	// if it was PSP, it means a (user/kernel space) process was interrupted

	task_create(task1, NULL, 1024, 1); // 1KB task stack
	task_create(task2, NULL, 1024, 2); // 1KB task stack
	task_create(task3, NULL, 1024, 3); // 1KB task stack
	task_create(task4, NULL, 1024, 4); // 1KB task stack

	os_start(); // doesn't return from this
}

void task1(void *data)
{
	uint32_t count = 4;
	while (1) {
		printf("This is task1, count: %lu\n", count);
		count += 4;
		task_delay_ms(2000);
	}
}

void task2(void *data)
{
	uint32_t count = 3;
	while (1) {
		printf("This is task2, count: %lu\n", count);
		count += 4;
		task_delay_ms(2000);
	}
}

void task3(void *data)
{
	uint32_t count = 2;
	while (1) {
		printf("This is task3, count: %lu\n", count);
		count += 4;
		task_delay_ms(2000);
	}
}
// T4 - T3 - T2 - T1 - Idle - T4
void task4(void *data)
{
	uint32_t count = 1;
	while (1) {
		printf("This is task4, count: %lu\n", count);
		count += 4;
		task_delay_ms(2000);
	}
}
